# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  namespace: default
  labels:
    app: hotel-service
spec:
  selector:
    matchLabels:
      app: hotel-service
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  hotel-service
      labels:
        app: hotel-service
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: hotel-service
        image: hotel404.azurecr.io/hotel-service:1 
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env: 
        - name: DB_CONNECTION_STRING
          valueFrom: 
            secretKeyRef: 
              name: constr 
              key: DB_CONNECTION_STRING


       
