apiVersion: v1
kind: Pod 
metadata: 
  name: probe
  labels: 
    test: probe 
spec: 
  containers: 
  - name: probe 
    image: docker.io/library/busybox:latest
    ports:  
    - containerPort: 7701
    startupProbe: 
      exec: 
        command: 
          - cat 
          - /tmp/started 
      periodSeconds: 10 
      failureThreshold: 3
    readinessProbe: 
      tcpSocket: 
        port: 7701
      initialDelaySeconds: 5
      periodSeconds: 2
    livenessProbe: 
      httpGet: 
        path: /health 
        port: 7701 
      initialDelaySeconds: 5
      periodSeconds: 2

