apiVersion: v1
kind: Pod 
metadata: 
  name: probe
  labels: 
    test: probe 
spec: 
  containers: 
  - name: probe 
    image: docker.io/library/busybox:latest
    command: ["sh", "-c", "touch /tmp/started && while true; do echo -e 'HTTP/1.1 200 OK\r\nContent-Length: 2\r\n\r\nOK'; sleep 1; done"]
    ports:  
    - containerPort: 7701
    startupProbe: 
      exec: 
        command: 
          - cat 
          - /tmp/started 
      periodSeconds: 10 
      failureThreshold: 3
    readinessProbe: 
      tcpSocket:
        port: 7701
      initialDelaySeconds: 5
      periodSeconds: 2
    livenessProbe: 
      httpGet:
        path: /   # Ändrat från /health till /
        port: 7701 
      initialDelaySeconds: 5
      periodSeconds: 2
